version: "3.1"
# https://docs.docker.com/compose/compose-file/

services:

  core-db:
    image: mysql:8.0.26
    container_name: core_mysql
    command: --max-allowed-packet=512M --performance-schema=FALSE --transaction-isolation=READ-COMMITTED --max-connections=500
    environment:
      - MYSQL_ROOT_PASSWORD=1a2b3c4d
    expose:
      - "3306"
    networks:
      - core-network
  core-be:
    build: .
    expose:
      - "8000"
    environment:
      - APPLICATION_TEXT="env text"
    networks:
      - core-network
      - jhub-network

volumes:
  core-dev-data:

networks:
  core-network:
    name: core-network
  jhub-network:
    name: jhub-network
    internal: false