spring:
  datasource:
    url: jdbc:mysql://localhost:3306/core?allowPublicKeyRetrieval=TRUE&useSSL=FALSE&createDatabaseIfNotExist=TRUE
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1a2b3c4d
  jpa:
    generate-ddl: true
    hibernate.ddl-auto: update
  messages:
    basename: message
    encoding: UTF-8
    fallback-to-system-locale=: true
logging:
  level:
    org:
      springframework: info