spring:
  profiles:
    active:
      - local_dev
  datasource:
    url: jdbc:mysql://core_mysql:3306/core?allowPublicKeyRetrieval=TRUE&useSSL=FALSE&createDatabaseIfNotExist=TRUE
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1a2b3c4d
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
logging:
  level:
    org:
      springframework: info
server:
  port: 8000
application:
  core:
    env: "build"